site_name: Scala Learning
repo_url: https://github.com/abdheshkumar/abdheshkumar.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/lightbulb
        name:
          Switch to light mode
nav:
  - Home: 'index.md'

# Docs
