site_name: Code, Learn, Repeat

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  icon:
    logo: logo
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/abdheshkumar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/abdhesh_rkg
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/abdhesh


# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.mark
  - def_list
  - attr_list
  - md_in_html
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - 'Abdhesh Kumar': 'index.md'
  - 'Kafka':
      - 'Kafka': 'kafka/index.md'
      - 'Kafka Producer': 'kafka/kafka-producer.md'
      - 'Kafka Consumer': 'kafka/kafka-consumer.md'
      - 'Kafka Tuning': 'kafka/kafka-tuning.md'
  - 'Scala':
      - 'Sbt testOnly': 'sbt-testonly.md'
      - 'Methods with variable arguments': 'methods-with-variable-arguments.md'
      - 'Pure/Total Functions': 'scala-pure-total-functions.md'
      - 'Multiple ways of handling an exception in scala': 'multiple-ways-of-handling-an-exception-in-scala.md'
      - 'When should you use Future, Future.successful and Future.failed': 'when-should-you-use-future-future-successful-future-failed.md'
      - 'What is kleisli or composition of monadic functions in scala': 'what-is-kleisli-or-composition-of-monadic-functions-in-scala.md'
      - 'For-Comprehension desugar': 'scala-for-comprehension-desugar.md'
      - 'Final case class': 'final-case-class.md'
  - 'Spark and Kafka':
      - 'Spark why should we not use inferschema=true with-dataframe': 'spark-why-should-we-not-use-inferschema-true-with-dataframe.md'
      - 'Easy and fast way of installing java scala and spark': 'easy-and-fast-way-of-installing-java-scala-and-spark.md'
      - 'Easy scalable and fault tolerant structured streaming from kafka to spark': 'easy-scalable-and-fault-tolerant-structured-streaming-from-kafka-to-spark.md'
      - 'Structured streaming kafka integration': 'structured-streaming-kafka-integration.md'
      - 'Kafka stream testing': 'kafka-stream-testing.md'

plugins:
  - sitemap

copyright: |
  &copy; 2023 <a href="https://github.com/abdheshkumar"  target="_blank" rel="noopener">Abdhesh Kumar</a>