site_name: Scala Learning
repo_url: https://github.com/abdheshkumar/abdheshkumar.github.io

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/lightbulb
        name:
          Switch to light mode
nav:
  - Home: 'index.md'
  - 'Scala':
      - 'Sbt testOnly': 'sbt-testonly.md'
      - 'Methods with variable arguments': 'methods-with-variable-arguments.md'
      - 'Pure/Total Functions': 'scala-pure-total-functions.md'
      - 'Multiple ways of handling an exception in scala': 'multiple-ways-of-handling-an-exception-in-scala.md'
      - 'When should you use Future, Future.successful and Future.failed': 'when-should-you-use-future-future-successful-future-failed.md'
      - 'What is kleisli or composition of monadic functions in scala': 'what-is-kleisli-or-composition-of-monadic-functions-in-scala.md'
  - 'Spark and Kafka':
      - 'Spark why should we not use inferschema=true with-dataframe': 'spark-why-should-we-not-use-inferschema-true-with-dataframe.md'
      - 'Easy and fast way of installing java scala and spark': 'easy-and-fast-way-of-installing-java-scala-and-spark.md'
      - 'Easy scalable and fault tolerant structured streaming from kafka to spark': 'easy-scalable-and-fault-tolerant-structured-streaming-from-kafka-to-spark.md'
      - 'Structured streaming kafka integration': 'structured-streaming-kafka-integration.md'
      - 'Kafka stream testing': 'kafka-stream-testing.md'

# Docs